server:
  port: 8301
spring:
  application:
    name: ribbon-service
  zipkin:  #配置分布式链路跟踪，配置收集日志的zipkin-server访问地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
service-url:  #对指定的服务进行配置
  user-service: http://user-service
  #ribbon:
    #ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
    #ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
    #OkToRetryOnAllOperations: true #对超时请求启用重试机制
    #MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
    #MaxAutoRetries: 1 # 切换实例后重试最大次数
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法
